---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: bus-ticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: bus-ticket/notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8006
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:SecureP@ssw0rd123@postgres:5432/notification_db"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt-secret
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:29092"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /notifications/health
              port: 8006
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: bus-ticket
spec:
  selector:
    app: notification-service
  ports:
    - port: 8006
      targetPort: 8006
