---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: bus-ticket
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: bus-ticket/user-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8002
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:SecureP@ssw0rd123@postgres:5432/user_db"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt-secret
            - name: REDIS_URL
              value: "redis://redis:6379"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /users/health
              port: 8002
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: bus-ticket
spec:
  selector:
    app: user-service
  ports:
    - port: 8002
      targetPort: 8002
